function h = setAxes(R,printGrid)
% parameters for the axes for geoshow for the HMA Albers projection
% projection
proj = HMAAlbers;
if verLessThan('map','5.0')
    Geoid = proj.geoid;
    Origin = proj.origin;
    MapParallels = proj.mapparallels;
else
    Geoid = proj.GeographicCRS.Spheroid;
    P = proj.ProjectionParameters;
    Origin = [P.LatitudeOfFalseOrigin P.LongitudeOfFalseOrigin 0];
    MapParallels = [P.LatitudeOf1stStandardParallel P.LatitudeOf2ndStandardParallel];
end
% print numbers on grid
if printGrid
    pgvalue = 'on';
else
    pgvalue = 'off';
end
% if R geographic
if contains(class(R),'geographic','IgnoreCase',true)
    delLabel = (round(max(R.LatitudeLimits),1)-round(min(R.LatitudeLimits),1))/2;
    latLabel = (round(min(R.LatitudeLimits),1):delLabel:round(max(R.LatitudeLimits),1));
    lonLabel = (round(min(R.LongitudeLimits),1):delLabel:round(max(R.LongitudeLimits),1));
    latLimit = R.LatitudeLimits;
    lonLimit = R.LongitudeLimits;
    h = axesm('eqaconicstd',...
        'Origin',Origin,...
        'Geoid',Geoid,...
        'MapParallels',MapParallels,...
        'MeridianLabel',pgvalue,...
        'ParallelLabel',pgvalue,...
        'MLabelLocation',lonLabel,...
        'PLabelLocation',latLabel,...
        'Grid',pgvalue,...
        'MapLatLimit',latLimit,...
        'MapLonLimit',lonLimit,...
        'MLineLocation',lonLabel,...
        'PLineLocation',latLabel,...
        'MLabelRound',-1,...
        'PLabelRound',-1,...
        'LabelFormat','signed');
else % R is projected
    [x,y] = meshgrid(R.XWorldLimits,R.YWorldLimits);
    if verLessThan('map','5.0')
        [lat,lon] = projinv(proj,x,y);
    else
        [lat,lon] = projinv(R.ProjectedCRS,x,y);
    end
    lonLimit = [min(lon(:)) max(lon(:))];
    latLimit = [min(lat(:)) max(lat(:))];
    lonLabel = round(min(lonLimit),1):.2:max(lonLimit);
    latLabel = sort(round(max(latLimit),1):-.2:min(latLimit));
    h = axesm('eqaconicstd',...
        'Origin',Origin,...
        'Geoid',Geoid,...
        'MapParallels',MapParallels,...
        'MeridianLabel',pgvalue,...
        'ParallelLabel',pgvalue,...
        'MLabelLocation',lonLabel,...
        'PLabelLocation',latLabel,...
        'Grid',pgvalue,...
        'MapLatLimit',latLimit,...
        'MapLonLimit',lonLimit,...
        'MLineLocation',lonLabel,...
        'PLineLocation',latLabel,...
        'MLabelRound',-1,...
        'PLabelRound',-1,...
        'LabelFormat','signed');
end

set(gca,'Box','off','Visible','off')
end